import { AudioController } from './modules/AudioController.js';
import { SidebarController } from './modules/SidebarController.js';
import { UIController } from './modules/UIController.js';
import { SearchController } from './modules/SearchController.js';

class App {
    constructor() {
        this.audio = new AudioController();
        this.sidebar = new SidebarController(this.audio);
        this.ui = new UIController();
        this.search = new SearchController(this.ui, this.sidebar);
    }

    init() {
        this.search.initialize();
        this.exposeGlobals();
    }

    exposeGlobals() {
        // Expose app instance for debugging and internal use
        window.app = this;

        // Expose functions required by HTML onclick attributes
        window.openEpisodeSidebar = (epId, segId) => this.sidebar.open(epId, segId);
        window.closeSidebar = () => this.sidebar.close();

        window.openInfoModal = () => this.ui.openInfoModal();
        window.closeInfoModal = () => this.ui.closeInfoModal();

        window.openEpisodeInfoModal = () => this.ui.openEpisodeInfoModal();
        window.closeEpisodeInfoModal = () => this.ui.closeEpisodeInfoModal();

        window.shareSidebarUrl = () => this.ui.shareSidebarUrl();

        window.loadEpisodes = (page) => this.search.loadEpisodes(page);

        // Legacy support for openEpisodeFromCard if it exists in static HTML
        window.openEpisodeFromCard = (episode) => this.sidebar.open(episode.id);

        // Legacy jumpToSegment (used in sidebar HTML generated by JS)
        // In SidebarController.js we used window.app.sidebar.jumpToSegment
        // But let's expose it globally just in case
        window.jumpToSegment = (segId, startTime) => this.sidebar.jumpToSegment(segId, startTime);
    }
}

document.addEventListener('DOMContentLoaded', () => {
    const app = new App();
    app.init();
});
